Repository mjurkowski/wdp-1904-03, pull requests merged in 2019-05, with the labels that each got.

#18 Task wdp190403 22
  package-lock.json
  package.json
  src/images/fotel_01.jpg
  src/images/fotel_02.jpg
  src/images/fotel_03.jpg
  src/images/jadalnia.jpg
  src/images/sypialnia.jpg
  src/index.html
  src/partials/20_section-promoted.html
  src/sass/components/_section--promoted.scss
  src/scripts/app.js
  src/scripts/promoted.js
  src/vendor/flickity.min.css
Labels: Ready for release

#2 bug-WDP190403-2
  src/partials/10_header.html
  src/sass/components/_header.scss
Labels: Ready for review

#25 Task wdp190403 23
  src/sass/components/_section--promoted.scss
  src/scripts/promoted.js
Labels: Ready for release

#7 Wdp190403-9
  src/sass/_variables.scss
  src/sass/components/_button.scss
  src/sass/components/_footer.scss
  src/sass/components/_header.scss
  src/sass/components/_panel-bar.scss
Labels: Ready for review

#30 Create changelog_Rafal_Pijet.md
  changelog_Rafal_Pijet.md
Labels: Ready for release

#29 Wdp 190403-10
  src/partials/10_header.html
  src/sass/components/_header.scss
Labels: Ready for review

#31 task-WDP190403-30
  src/partials/80_section-brands.html
  src/sass/components/_section--brands.scss
  src/scripts/app.js
  src/scripts/carousels.js
Labels: Required changes / reabase

#32 task-WDP190403-33
  src/partials/85_section-feedback.html
  src/sass/components/_section--feedback.scss
  src/scripts/app.js
  src/scripts/feedback.js
Labels: Ready for review

#33 task-WDP190403-31
  src/sass/components/_section--brands.scss
Labels: Ready for review

#24 Wdp190403-18
  src/index.html
  src/partials/50_section-products.html
  src/sass/components/_panel-bar.scss
  src/sass/components/_product-box.scss
  src/sass/components/_section--products.scss
  src/sass/style.scss
  src/scripts/app.js
  vendor/flickity/flickity.min.css
Labels: Ready for review

#34 Marcin Polonis' part of the project
  changelog_Marcin_Polonis.md
Labels: Ready for release

#35 Fix my WDP190403-2 task
  src/sass/components/_header.scss
Labels: Ready for release

#36 Marcin.polonis.todo
  changelog_Marcin_Polonis.md
Labels: Ready for release

#39 Changelog_Mateusz_Lewartowski - Project Description
  changelog_Mateusz_Lewartowski.md
Labels: Ready for release

#40 Create changelog_Tomasz_Rusin.md
  changelog_Tomasz_Rusin.md
Labels: Ready for review, enhancement

#37 Wdp190403-24
  src/index.html
  src/partials/40_section-deals.html
  src/partials/50_section-products.html
  src/sass/components/_section--deals.scss
  src/sass/style.scss
Labels: Ready for review
